version: '3'
services:
  messaging:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
  mysql:
    image: 'mysql'
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: craft
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
    volumes:
      - db-data:/var/lib/mysql

  front_end:
    container_name: front_end
    build: ./front_end
    ports:
      - 5000:5000


## Placeholder for the persistent db storage
volumes:
  db-data: