version: '3'
services:
  messaging:
    image: 'rabbitmq:3-management'
    ports:
        - 5672:5672
  mysql:
    image: 'mysql'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
  admin:
    image: adminer
    ports:
      - "8080:8080"

  front_end:
    build: ./front_end
    ports:
      - 5000:5000

  back_end:
    image:
    build: ./back_end
    ports:
      - 5672:5672
