version: "3"
services:
  backend:
    build: ./back_end
    networks:
      - my_network
    ports:
      - 3000:3000
    environment:
      TEST_ENV: db
    depends_on:
      - db
  frontend:
    build: ./front_end
    networks:
      - my_network
    ports:
      - 5000:5000
  db:
    image: "mysql:5.7"
    networks:
      - my_network
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: library

  messaging:
    image: "rabbitmq:3-management"
    restart: always
    networks:
      - my_network
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: meJvpzPsMkmTrc3g
      RABBITMQ_ERLANG_COOKIE: uDFReJY9e35DZZXL
    ports:
      - "5673:5672"
      - "15673:15672"

  messaging2:
    image: "rabbitmq:3-management"
    hostname: messaging2
    links:
      - messaging
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: meJvpzPsMkmTrc3g
      RABBITMQ_ERLANG_COOKIE: uDFReJY9e35DZZXL
    ports:
      - "5672:5672"
      - "15672:15672"

  messaging3:
    image: "rabbitmq:3-management"
    hostname: messaging3
    links:
      - messaging
      - messaging2
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: meJvpzPsMkmTrc3g
      RABBITMQ_ERLANG_COOKIE: uDFReJY9e35DZZXL
    ports:
      - "5673:5672"
      - "15673:15672"

networks:
  my_network:
    driver: bridge
