version: '3'
services:
  messaging:
    image: 'rabbitmq:3-management'
    ports:
    - 6000:6000
    build: ./messaging
  #mysql:
   # image: 'mysql'
   # environment:
   #   MYSQL_ROOT_PASSWORD: changeme
  #front_end:
    #build: ./front_end
    #ports:
     # - 5000:5000
