version: "3"
services:
  backend:
    build: ./flask_backend
    networks:
      - my_network
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      RABBITMQ_HOST: messaging
      RABBITMQ_USER: example
      RABBITMQ_PASSWORD: meJvpzPsMkmTrc3g

    depends_on:
      - db
  frontend:
    build: ./flask_frontend
    networks:
      - my_network
    ports:
      - 3000:3000
  db:
    image: "mysql:5.7"
    networks:
      - my_network
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: library
  messaging:
    image: "rabbitmq:3-management"
    restart: always
    networks:
      - my_network
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: meJvpzPsMkmTrc3g
      RABBITMQ_ERLANG_COOKIE: uDFReJY9e35DZZXL
    ports:
      - '15672:15672'

networks:
  my_network:
    driver: bridge
