version: '3'
services:
  messaging:
    image: 'rabbitmq:3-management'
  mysql:
    image: 'mysql'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme


  front_end:
    build: ./front_end
    ports:
      - 6000:6000


