version: "3"
services:
  backend:
    build: ./flask_backend
    networks:
      - my_network
    ports:
      - 5000:5000
    environment:
      TEST_ENV: db
    depends_on:
      - db
  frontend:
    build: ./flask_frontend
    networks:
      - my_network
    ports:
      - 3000:3000
  db:
    image: "mysql:5.7"
    networks:
      - my_network
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: library
  messaging:
    image: "rabbitmq:3-management"
    networks:
      - my_network
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: meJvpzPsMkmTrc3g
      RABBITMQ_ERLANG_COOKIE: uDFReJY9e35DZZXL

networks:
  my_network:
    driver: bridge
