version: '3'
services:
  messaging:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

  mysql:
    image: 'mysql'
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306

    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
      #MYSQL_USERNAME: 'admin'
      #MYSQL_ROOT_PASSWORD: 'admin'
    links:
      - mysql:mysql
    ports:
      - 8080:80
    #volumes:
    #  -  /sessions


  front_end:
    container_name: front_end
    build: ./front_end
    ports:
      - 5000:5000

  back_end:
    container_name: back_end
    build: ./back_end
    image: python:3.7-alpine

## Placeholder for the persistent db storage
volumes:
  db-data: